# Generated by Django 5.2 on 2025-05-09 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 15, 9, 24, 514969, tzinfo=datetime.timezone.utc)),
        ),
    ]
