# Generated by Django 5.2 on 2025-05-18 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpverification_expiry_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mobile_number',
            new_name='mobile_no',
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 9, 45, 3, 309827, tzinfo=datetime.timezone.utc)),
        ),
    ]
