# Generated by Django 5.2 on 2025-05-22 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_mobile_number_customuser_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 22, 12, 59, 47, 570886, tzinfo=datetime.timezone.utc)),
        ),
    ]
