# Generated by Django 5.2 on 2025-05-23 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_otpverification_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 23, 7, 35, 23, 603459, tzinfo=datetime.timezone.utc)),
        ),
    ]
