# Generated by Django 5.2 on 2025-05-25 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_mobile_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 25, 12, 20, 27, 181452, tzinfo=datetime.timezone.utc)),
        ),
    ]
