# Generated by Django 5.2 on 2025-06-02 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 2, 21, 16, 47, 298213, tzinfo=datetime.timezone.utc)),
        ),
    ]
