# Generated by Django 5.2 on 2025-06-08 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_otpverification_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 8, 13, 21, 55, 250997, tzinfo=datetime.timezone.utc)),
        ),
    ]
