# Generated by Django 5.2 on 2025-06-09 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_otpverification_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 9, 7, 52, 44, 101846, tzinfo=datetime.timezone.utc)),
        ),
    ]
