# Generated by Django 5.2 on 2025-06-11 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_otpverification_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 14, 36, 57, 983078, tzinfo=datetime.timezone.utc)),
        ),
    ]
