# Generated by Django 5.2 on 2025-08-10 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_otpverification_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 10, 14, 36, 33, 25786, tzinfo=datetime.timezone.utc)),
        ),
    ]
