# Generated by Django 5.2 on 2025-08-12 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_otpverification_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 13, 37, 6, 932378, tzinfo=datetime.timezone.utc)),
        ),
    ]
