# Generated by Django 5.2 on 2025-08-13 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_otpverification_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 11, 53, 24, 392414, tzinfo=datetime.timezone.utc)),
        ),
    ]
