# Generated by Django 5.2 on 2025-08-14 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 14, 14, 59, 19, 872656, tzinfo=datetime.timezone.utc)),
        ),
    ]
