# Generated by Django 5.2 on 2025-08-16 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_otpverification_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 7, 36, 39, 345745, tzinfo=datetime.timezone.utc)),
        ),
    ]
