# Generated by Django 5.2 on 2025-08-22 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_otpverification_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 16, 5, 10, 225457, tzinfo=datetime.timezone.utc)),
        ),
    ]
