# Generated by Django 5.2 on 2025-08-29 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_otpverification_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 29, 8, 3, 47, 710788, tzinfo=datetime.timezone.utc)),
        ),
    ]
