# Generated by Django 5.2 on 2026-01-26 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_otpverification_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 26, 11, 30, 22, 458775, tzinfo=datetime.timezone.utc)),
        ),
    ]
