# Generated by Django 5.2 on 2026-01-27 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_otpverification_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 27, 8, 36, 35, 615073, tzinfo=datetime.timezone.utc)),
        ),
    ]
