# Generated by Django 5.2 on 2026-02-06 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_otpverification_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 6, 15, 33, 49, 230655, tzinfo=datetime.timezone.utc)),
        ),
    ]
