# Generated by Django 5.2 on 2025-08-16 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_product_is_listed'),
        ('userpanel', '0002_alter_address_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('RP', 'Razor Pay'), ('WP', 'Wallet Pay'), ('COD', 'Cash on Delivery')], max_length=4)),
                ('payment_status', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=200, null=True)),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='userpanel.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Payment_Failed', 'Payment Failed'), ('Processing', 'Processing'), ('On_Hold', 'On Hold'), ('Shipped', 'Shipped'), ('On_the_Way', 'On the Way'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return_Requested', 'Return Requested'), ('Returned', 'Returned'), ('Refunded', 'Refunded')], default='Pending', max_length=24)),
                ('item_payment_status', models.CharField(choices=[('Pending', 'pending'), ('Paid', 'paid'), ('Unpaid', 'unpaid'), ('Failed', 'failed'), ('Refunded', 'refunded'), ('Processing', 'processing')], default='pending', max_length=10)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('OPM', 'Order Placed by Mistake'), ('CMM', 'Changed My Mind'), ('DTL', 'Delivery Time Was Too Long'), ('ILN', 'Item No Longer Needed'), ('OWI', 'Ordered Wrong Item'), ('OFS', 'Item Not Available or Out of Stock'), ('DP', 'Received Damaged Product'), ('RII', 'Received Incorrect Item'), ('NME', "Product Didn't Meet Expectations"), ('QC', 'Quality Concerns'), ('SCI', 'Size/Color Issue')], max_length=4, null=True)),
                ('custom_cancellation_reason', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_bill_generated', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='product.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.orderitem')),
            ],
        ),
    ]
