# Generated by Django 5.2 on 2025-08-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_payment_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Paid', 'paid'), ('Unpaid', 'unpaid'), ('Failed', 'failed'), ('Refunded', 'refunded'), ('Processing', 'processing'), ('Cancelled', 'cancelled')], default='pending', max_length=10),
        ),
    ]
