# Generated by Django 5.2 on 2026-01-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('RP', 'Razor Pay'), ('WP', 'Wallet Pay'), ('COD', 'Cash on Delivery'), ('PP', 'PayPal')], max_length=4),
        ),
    ]
